/* Generated by reswrap version 3.0.0 */

/* created by reswrap from file ../icons/small_calc.bmp */
extern const unsigned char small_calc[];

/* created by reswrap from file ../icons/big_calc.bmp */
extern const unsigned char big_calc[];

